name: naqi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  google_nav_bar: ^5.0.6
  awesome_dialog: ^3.2.0
  smooth_page_indicator: ^1.2.0
  badges: ^3.1.2
  url_launcher: ^6.3.0
  flutter_speed_dial: ^7.0.0
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^5.5.0

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/logo2.jpg
    - images/background.jpg
    - images/object.png
    - images/whiteLogo.svg
    - images/background2.jpeg
    - images/profile.jpg
    - images/profile.svg
    - images/profile.png
    - images/bg.jpg
    - images/Group1.png
    - images/Group2.png
    - images/Group3.png
    - icons/user.svg
    - icons/user.png
    - icons/users.svg
    - icons/search.svg
    - icons/globe.svg
    - icons/bell.svg
    - icons/alert.svg
    - icons/like.svg
    - icons/userp.svg
    - icons/alert.svg
    - icons/userss.svg
    - icons/like.svg
    - icons/facebook.svg
    - icons/twitter.svg
    - icons/google.svg
    - icons/instagram.svg
    - icons/sms.svg
    - icons/phone.svg
    - icons/settings.svg
    - icons/pro.svg
    - icons/del.svg
    - images/logo.svg
    - images/Bottle of water (2).gif
    - images/Delivery address.gif
    - images/Refreshing.gif
    - images/de.gif

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
